[package]
name = "aspen-popef"
version = "0.1.0"
edition = "2024"

[dependencies]
capnp = "0.25"

[build-dependencies]
capnpc = "0.25"

[dev-dependencies]
zerocopy = { workspace = true }
lz4_flex = "0.12.0"
